### ISSUE TITLE
Eslint : es6 and jsx compliants

### ISSUE THREAD

**Issue by duvillierA** [slyg/potier#2]
Hi Sylvain,

I recommend you to have a look at Eslint as linter. It manages Jsx/es6.
Good job for this project :+1:

**Comment by slyg** [comment]
I miss some karma or acceptance tests but it's just a playground you know, I might try elm on it too :bowtie:
Btw, done at a39cd7fc8d99b09012ea7fecb3a5f6652f7d0e9e.

**Comment by duvillierA** [comment]
Well done ;)
